#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PINQTest
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="smartstardb")]
	public partial class SmartStarNamekDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public SmartStarNamekDataContext() : 
				base(global::PINQTest.Properties.Settings.Default.smartstardbConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public SmartStarNamekDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SmartStarNamekDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SmartStarNamekDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SmartStarNamekDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Environmental> Environmentals
		{
			get
			{
				return this.GetTable<Environmental>();
			}
		}
		
		public System.Data.Linq.Table<Circuit> Circuits
		{
			get
			{
				return this.GetTable<Circuit>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllInsideTemp")]
		public ISingleResult<GetAllInsideTempResult> GetAllInsideTemp()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetAllInsideTempResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TestProc")]
		public ISingleResult<TestProcResult> TestProc()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<TestProcResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllCircuitByTS")]
		public ISingleResult<GetAllCircuitByTSResult> GetAllCircuitByTS()
		{
            this.CommandTimeout = 300;
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetAllCircuitByTSResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Environmental")]
	public partial class Environmental
	{
		
		private string _TimestampUTC;
		
		private System.Nullable<decimal> _insideTemp;
		
		private System.Nullable<decimal> _outsideTemp;
		
		private System.Nullable<decimal> _insideHumidity;
		
		private System.Nullable<decimal> _outsideHumidity;
		
		private System.Nullable<decimal> _windSpeed;
		
		private System.Nullable<decimal> _windDirectionDegrees;
		
		private System.Nullable<decimal> _windGust;
		
		private System.Nullable<decimal> _windGustDirectionDegrees;
		
		private System.Nullable<decimal> _rainRate;
		
		private System.Nullable<decimal> _rain;
		
		private System.Nullable<decimal> _windChill;
		
		private System.Nullable<decimal> _heatindex;
		
		public Environmental()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimestampUTC", DbType="VarChar(10)")]
		public string TimestampUTC
		{
			get
			{
				return this._TimestampUTC;
			}
			set
			{
				if ((this._TimestampUTC != value))
				{
					this._TimestampUTC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_insideTemp", DbType="Decimal(10,5)")]
		public System.Nullable<decimal> insideTemp
		{
			get
			{
				return this._insideTemp;
			}
			set
			{
				if ((this._insideTemp != value))
				{
					this._insideTemp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outsideTemp", DbType="Decimal(10,5)")]
		public System.Nullable<decimal> outsideTemp
		{
			get
			{
				return this._outsideTemp;
			}
			set
			{
				if ((this._outsideTemp != value))
				{
					this._outsideTemp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_insideHumidity", DbType="Decimal(10,5)")]
		public System.Nullable<decimal> insideHumidity
		{
			get
			{
				return this._insideHumidity;
			}
			set
			{
				if ((this._insideHumidity != value))
				{
					this._insideHumidity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_outsideHumidity", DbType="Decimal(10,5)")]
		public System.Nullable<decimal> outsideHumidity
		{
			get
			{
				return this._outsideHumidity;
			}
			set
			{
				if ((this._outsideHumidity != value))
				{
					this._outsideHumidity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_windSpeed", DbType="Decimal(10,5)")]
		public System.Nullable<decimal> windSpeed
		{
			get
			{
				return this._windSpeed;
			}
			set
			{
				if ((this._windSpeed != value))
				{
					this._windSpeed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_windDirectionDegrees", DbType="Decimal(10,5)")]
		public System.Nullable<decimal> windDirectionDegrees
		{
			get
			{
				return this._windDirectionDegrees;
			}
			set
			{
				if ((this._windDirectionDegrees != value))
				{
					this._windDirectionDegrees = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_windGust", DbType="Decimal(10,5)")]
		public System.Nullable<decimal> windGust
		{
			get
			{
				return this._windGust;
			}
			set
			{
				if ((this._windGust != value))
				{
					this._windGust = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_windGustDirectionDegrees", DbType="Decimal(10,5)")]
		public System.Nullable<decimal> windGustDirectionDegrees
		{
			get
			{
				return this._windGustDirectionDegrees;
			}
			set
			{
				if ((this._windGustDirectionDegrees != value))
				{
					this._windGustDirectionDegrees = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rainRate", DbType="Decimal(10,5)")]
		public System.Nullable<decimal> rainRate
		{
			get
			{
				return this._rainRate;
			}
			set
			{
				if ((this._rainRate != value))
				{
					this._rainRate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rain", DbType="Decimal(10,5)")]
		public System.Nullable<decimal> rain
		{
			get
			{
				return this._rain;
			}
			set
			{
				if ((this._rain != value))
				{
					this._rain = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_windChill", DbType="Decimal(10,5)")]
		public System.Nullable<decimal> windChill
		{
			get
			{
				return this._windChill;
			}
			set
			{
				if ((this._windChill != value))
				{
					this._windChill = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_heatindex", DbType="Decimal(10,5)")]
		public System.Nullable<decimal> heatindex
		{
			get
			{
				return this._heatindex;
			}
			set
			{
				if ((this._heatindex != value))
				{
					this._heatindex = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Circuit")]
	public partial class Circuit
	{
		
		private string _CircuitName;
		
		private System.Nullable<int> _CircuitNumber;
		
		private string _TimestampUTC;
		
		private System.Nullable<decimal> _RealPowerWatts;
		
		private System.Nullable<decimal> _ApparentPowerVAs;
		
		public Circuit()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CircuitName", DbType="VarChar(50)")]
		public string CircuitName
		{
			get
			{
				return this._CircuitName;
			}
			set
			{
				if ((this._CircuitName != value))
				{
					this._CircuitName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CircuitNumber", DbType="Int")]
		public System.Nullable<int> CircuitNumber
		{
			get
			{
				return this._CircuitNumber;
			}
			set
			{
				if ((this._CircuitNumber != value))
				{
					this._CircuitNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimestampUTC", DbType="VarChar(10)")]
		public string TimestampUTC
		{
			get
			{
				return this._TimestampUTC;
			}
			set
			{
				if ((this._TimestampUTC != value))
				{
					this._TimestampUTC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RealPowerWatts", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> RealPowerWatts
		{
			get
			{
				return this._RealPowerWatts;
			}
			set
			{
				if ((this._RealPowerWatts != value))
				{
					this._RealPowerWatts = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApparentPowerVAs", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> ApparentPowerVAs
		{
			get
			{
				return this._ApparentPowerVAs;
			}
			set
			{
				if ((this._ApparentPowerVAs != value))
				{
					this._ApparentPowerVAs = value;
				}
			}
		}
	}
	
	public partial class GetAllInsideTempResult
	{
		
		private System.Nullable<decimal> _insideTemp;
		
		public GetAllInsideTempResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_insideTemp", DbType="Decimal(10,5)")]
		public System.Nullable<decimal> insideTemp
		{
			get
			{
				return this._insideTemp;
			}
			set
			{
				if ((this._insideTemp != value))
				{
					this._insideTemp = value;
				}
			}
		}
	}
	
	public partial class TestProcResult
	{
		
		private System.Nullable<decimal> _RealPowerWatts;
		
		public TestProcResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RealPowerWatts", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> RealPowerWatts
		{
			get
			{
				return this._RealPowerWatts;
			}
			set
			{
				if ((this._RealPowerWatts != value))
				{
					this._RealPowerWatts = value;
				}
			}
		}
	}
	
	public partial class GetAllCircuitByTSResult
	{
		
		private System.Nullable<decimal> _Power;
		
		private string _TimestampUTC;
		
		public GetAllCircuitByTSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Power", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> Power
		{
			get
			{
				return this._Power;
			}
			set
			{
				if ((this._Power != value))
				{
					this._Power = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimestampUTC", DbType="VarChar(10)")]
		public string TimestampUTC
		{
			get
			{
				return this._TimestampUTC;
			}
			set
			{
				if ((this._TimestampUTC != value))
				{
					this._TimestampUTC = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
